version: 2.1

orbs:
  hokusai: artsy/hokusai@0.7

not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release

only_master: &only_master
  context: hokusai
  filters:
    branches:
      only: master

only_release: &only_release
  context: hokusai
  filters:
    branches:
      only: release

workflows:
  build-deploy:
    jobs:
      - hokusai/push:
          name: push-staging-image
          <<: *only_master

      - hokusai/deploy-staging:
          <<: *only_master
          project-name: team
          requires:
            - push-staging-image

      - hokusai/deploy-production:
          <<: *only_release
