---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: team-web
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: team
        component: web
        layer: application
      name: team-web
    spec:
      containers:
        - name: team-web
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: production
            - name: TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: team-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/team:staging
          imagePullPolicy: Always
          ports:
            - name: team-http
              containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              port: team-http
              path: /api/health
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
        - name: team-nginx
          image: artsy/docker-nginx:1.14.2
          ports:
            - name: nginx-http
              containerPort: 80
            - name: nginx-https
              containerPort: 443
          readinessProbe:
            tcpSocket:
              port: nginx-http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5 && /usr/sbin/nginx -s quit"]
          env:
            - name: "NGINX_DEFAULT_CONF"
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: default
          volumeMounts:
            - name: nginx-secrets
              mountPath: /etc/nginx/ssl
      volumes:
        - name: nginx-secrets
          secret:
            secretName: nginx-secrets
            defaultMode: 420
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - foreground

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: team-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: team-web
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: team-external-auth
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/api/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://stagingapi.artsy.net/oauth2/authorize?client_id={{ APP_ID }}&redirect_uri=$host/oauth2/callback?redirect_to=$escaped_request_uri"
spec:
  rules:
    - host: team-staging.artsy.net
      http:
        paths:
          - path: /
            backend:
              serviceName: team-web-internal
              servicePort: http

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: team-oauth
spec:
  rules:
    - host: team-staging.artsy.net
      http:
        paths:
          - path: /oauth2
            backend:
              serviceName: team-web-internal
              servicePort: http
